pipeline {
    
    agent any

    tools {
       jdk "Java"
    }
    
    stages {

        stage('CheckOut Git') { // for display purposes
            steps {
                echo "Iniciando CheckOut de Git"

                // Obtiene el código del GitHub repository
                // git branch:'main', url: 'https://github.com/RaulDeVicente/PoCNatDevOps.git'
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/main']],
                    extensions: [[$class: 'RelativeTargetDirectory',
                    relativeTargetDir: 'GISSPoCNatDevOps']],
                    userRemoteConfigs: [[url: 'https://github.com/RaulDeVicente/PoCNatDevOps.git']]])

                echo "Finalizando CheckOut de Git"
            }
        }

        stage('Deploy en Desarrollo') {
            steps {
                echo "Iniciando Deploy en Desarrollo"

                // Despliega el código en el servidor de Natural.
                // C:\apache-ant-1.10.11\bin\ant.bat -file deploy.xml -Dnatural.ant.project.rootdir=../.. -lib C:\workspaces\DevOpsNat\NO4Jenkins\deploy build && exit %%ERRORLEVEL%%

                Parametros = '-file GISSPoCNatDevOps/GISSPoCNatDevOps/deploy.xml -Dnatural.ant.project.rootdir=../.. -lib C:/workspaces/DevOpsNat/NO4Jenkins/deploy build && exit %%ERRORLEVEL%%'

//                withAnt(installation: 'Ant Local', jdk: 'Java') {
//                    if (isUnix()) {
//                        sh "ant ${Parametros}"
//                    }
//                    else {
//                        bat "ant ${Parametros}"
//                    }
//                }

                echo "Finalizando Deploy en Desarrollo"
            }
        }

        stage('Análisis de código (Kiuwan)') {

            steps {
                echo "Iniciando Análisis de código (Kiuwan)"

                kiuwan connectionProfileUuid: 'pqvj-J6Ik',
                    applicationName_dm: 'GISSPoCNatDevOps',
                    selectedMode: 'DELIVERY_MODE',
                    sourcePath: 'GISSPoCNatDevOps/GISSPoCNatDevOps',
                    indicateLanguages_dm: true,
                    languages_dm: 'natural',
                    waitForAuditResults_dm: true

                echo "Finalizando Análisis de código (Kiuwan)"
            }
        }
    }
}